# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  

steps:
- script: |
    dotnet restore
    dotnet build --configuration Release

- task: DotNetCoreCLI@2
  condition: and(succeeded(), eq(variables.isMain, true))
  inputs:
    command: publish
    arguments: '--configuration Release --output publish_output'
    projects: 'Company.Frontend/Company.Frontend.csproj'
    publishWebProjects: false
    modifyOutputPath: false
    zipAfterPublish: false
    
- task: ArchiveFiles@2
  displayName: "Archive files"
  condition: and(succeeded(), eq(variables.isMain, true))
  inputs:
    rootFolderOrFile: "$(System.DefaultWorkingDirectory)/publish_output"
    includeRootFolder: false
    archiveFile: "$(System.DefaultWorkingDirectory)/build$(Build.BuildId).zip"

- task: AzureWebApp@1
  inputs:
    appType: 'webAppLinux'
    appName: 'jasonlinux'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'